version: '3.4'

services:
  mfwikipedia:
    image: mfwikipedia
    build:
      context: wikipedia/mf-wikipedia
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4214:4214
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
